#!/bin/bash
# usage: aws/bootstrap_box.sh <instance-id> <launcher-s3-key> <s3-prefix> <env-file-contents-base64>
set -u; export AWS_PROFILE=${AWS_PROFILE:-default}; IID=$1; LNCHKEY=$2; PREFIX=$3; ENVB64=$4
for i in $(seq 1 60); do st=$(aws ssm describe-instance-information --filters Key=InstanceIds,Values=$IID --query 'InstanceInformationList[0].PingStatus' --output text 2>/dev/null); [ "$st" = "Online" ] && break; sleep 15; done
TGZ=$(aws s3 presign s3://${FLYCRITIC_BUCKET:?set FLYCRITIC_BUCKET}/flycritic.tgz --expires-in 7200); LNCH=$(aws s3 presign s3://${FLYCRITIC_BUCKET:?set FLYCRITIC_BUCKET}/$LNCHKEY --expires-in 7200); WD=$(aws s3 presign s3://${FLYCRITIC_BUCKET:?set FLYCRITIC_BUCKET}/watchdog.sh --expires-in 7200)
CMD=$(aws ssm send-command --instance-ids $IID --document-name AWS-RunShellScript --timeout-seconds 3600 \
  --parameters "commands=[\"cd /home/ubuntu\",\"curl -sSL -o flycritic.tgz '$TGZ'\",\"curl -sSL -o flycritic.train_launcher.sh '$LNCH'\",\"curl -sSL -o watchdog.sh '$WD'\",\"for x in launch_fix5.sh launch_cl.sh; do curl -sSL -o \$x \"\$(aws s3 presign s3://${FLYCRITIC_BUCKET:?set FLYCRITIC_BUCKET}/\$x --expires-in 3600 2>/dev/null || echo none)\" || true; done\",\"echo $ENVB64 | base64 -d > launch.env\",\"tar xzf flycritic.tgz 2>/dev/null || true\",\"chown -R ubuntu:ubuntu fly-critic flycritic.train_launcher.sh watchdog.sh launch.env\",\"until test -f /home/ubuntu/READY; do sleep 5; done\",\"touch /home/ubuntu/launcher.log && chown ubuntu:ubuntu /home/ubuntu/launcher.log\",\"sudo -u ubuntu -i bash -c 'cd /home/ubuntu && set -a && . /home/ubuntu/launch.env && set +a && nohup bash /home/ubuntu/flycritic.train_launcher.sh >> /home/ubuntu/launcher.log 2>&1 &'\",\"sudo -u ubuntu -i bash -c 'nohup bash /home/ubuntu/watchdog.sh $PREFIX > /home/ubuntu/watchdog.log 2>&1 &'\",\"sleep 200; tail -n 3 /home/ubuntu/launcher.log | cut -c1-100; pgrep -fc 'flycritic'\"]" --query 'Command.CommandId' --output text)
for i in $(seq 1 40); do st=$(aws ssm get-command-invocation --command-id $CMD --instance-id $IID --query Status --output text 2>/dev/null); [ "$st" = "Success" ] || [ "$st" = "Failed" ] && break; sleep 15; done
aws ssm get-command-invocation --command-id $CMD --instance-id $IID --query '[Status,StandardOutputContent,StandardErrorContent]' --output text | grep -vE "^$" | tail -6 | cut -c1-110
